import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Provider } from "react-redux";

import SearchMessage from "../components/common/SearchMessage/SearchMessage";
import Container from "../components/map/Container/Container";
import Geolocation from "../components/map/Geolocation/Geolocation";
import styles from "../styles/Home.module.css";
import { store } from "../utils/store";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>FindMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <div className={styles.container}>
          <SearchMessage />
          <Container />
          <Geolocation />
        </div>
      </Provider>
    </>
  );
};

export default Home;
