import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import SearchMessage from "../components/common/SearchMessage/SearchMessage";
import Container from "../components/map/Container/Container";
import Geolocation from "../components/map/Geolocation/Geolocation";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>FindMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <SearchMessage />
        <Container />
        <Geolocation />
      </div>
    </>
  );
};

export default Home;
